id: P46E66418
initial_creation_type: input
source_metadata:
  Title: Journal of Indian and Buddhist studies
  Editor: Katsumi Mimaki
  Publisher: Journal of Indian and Buddhist studies
  Place of Publication: Tokyo
  Year: '1977'
  Ṣaṇmukhī dhāraṇī:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T15:57:09.890186'
last_modified_at: '2022-03-08T15:57:09.890194'
